version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-api
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=orijinplus
      - DB_USER=root
      - DB_PASSWORD=secret
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres-db
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=orijinplus
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
